version: '3'
services:
  app:
    container_name: docker-server2
    restart: always
    build: .
    ports:
      - '5500:5500'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'